const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.connectOverCDP(process.env.CHROME_CDP_URL || 'http://127.0.0.1:9222');
  const context = browser.contexts()[0];
  const page = context.pages().find(candidate => candidate.url().includes('crazy-tuktuk.vercel.app')) || context.pages()[0];
  if (!page) throw new Error('Open CrazyTukuk in Brave before running this test');
  const errors = [];
  const railway = [];
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  page.on('request', request => { if (request.url().includes('railway.app')) railway.push(request.url()); });
  await page.bringToFront();
  await page.reload({ waitUntil: 'networkidle' });
  await page.locator('#titleTournament').click();
  await page.waitForTimeout(1_000);
  await page.locator('#tournamentGarage').click({ force: true });
  await page.waitForTimeout(1_000);
  await page.locator('#garagePanel').evaluate(element => { element.hidden = false; });
  await page.locator('.garage-driver-card').first().click({ force: true });
  await page.locator('#garageCreateDriver').click({ force: true });
  await page.locator('#garageCreateDriver').click({ force: true });
  await page.locator('#garageCreateDriver').click({ force: true });
  await page.waitForTimeout(2_000);
  const status = await page.locator('#agentTopStatus').textContent();
  if (!/ACTIVE|ON TRIP|EVALUATING|FARE|QUEUED/i.test(status || '')) throw new Error('Agent did not start: ' + status);
  if (railway.length) throw new Error('Railway requests detected: ' + railway.join(', '));
  const relevantErrors = errors.filter(error => !error.includes('ObjectMultiplex'));
  if (relevantErrors.length) throw new Error('Console errors detected: ' + relevantErrors.join('\n'));
  console.log('PASS Agent CDP smoke: status=' + status.trim() + ', railwayRequests=0, consoleErrors=0');
  await browser.close();
})().catch(error => { console.error('FAIL ' + error.message); process.exit(1); });
