const { randomUUID } = require('node:crypto');
const { requireSession } = require('../_lib/auth');
const { withDatabaseTransaction, trustedNow } = require('../_lib/db');
const { bangkokDayWindow } = require('../_lib/dailyPeriod');

module.exports = async function handler(request,response) {
  if(request.method!=='POST')return response.status(405).json({error:'method_not_allowed'});
  const session=await requireSession(request); if(!session)return response.status(401).json({error:'agent_session_required'});
  const body=request.body||{}; if(typeof body.name!=='string'||!body.name.trim()||typeof body.persona!=='string'||!body.persona.trim())return response.status(400).json({error:'invalid_agent_profile'});
  try { const result=await withDatabaseTransaction(async client=>{const now=await trustedNow(client); const {key,start,end}=bangkokDayWindow(now); const shift=(await client.query(`INSERT INTO daily_shifts (id,shift_key,status,starts_at,ends_at) VALUES ($1,$2,'ACTIVE',$3,$4) ON CONFLICT (shift_key) DO UPDATE SET starts_at=CASE WHEN daily_shifts.status IN ('FINALIZING','COMPLETE') THEN daily_shifts.starts_at ELSE EXCLUDED.starts_at END, ends_at=CASE WHEN daily_shifts.status IN ('FINALIZING','COMPLETE') THEN daily_shifts.ends_at ELSE EXCLUDED.ends_at END, status=CASE WHEN daily_shifts.status IN ('FINALIZING','COMPLETE') THEN daily_shifts.status ELSE 'ACTIVE' END RETURNING *`,[randomUUID(),key,start,end])).rows[0]; const agent=(await client.query(`INSERT INTO agents (id,owner_wallet,name,persona,dflow_wallet_name,wallet_public_key) VALUES ($1,$2,$3,$4,$5,$2) ON CONFLICT(owner_wallet) DO UPDATE SET name=EXCLUDED.name,persona=EXCLUDED.persona RETURNING id`,[randomUUID(),session.owner_wallet,body.name.trim(),body.persona.trim(),`auth-${session.owner_wallet.slice(0,28)}`])).rows[0]; await client.query(`INSERT INTO agent_shift_states (id,shift_id,agent_id,status,bankroll,next_action_at) VALUES ($1,$2,$3,'ACTIVE',20,now()) ON CONFLICT(shift_id,agent_id) DO NOTHING`,[randomUUID(),shift.id,agent.id]); return {agentId:agent.id,shift};}); return response.status(201).json(result); } catch(e){console.error('agent registration failed',e);return response.status(503).json({error:'agent_registration_unavailable'});}
};
