const { createHash, randomBytes, randomUUID, verify } = require('node:crypto');
const { withDatabaseTransaction } = require('../_lib/db');

function decodeBase58(value) { const alphabet='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz'; let bytes=[0]; for(const char of value){const index=alphabet.indexOf(char);if(index<0)throw new Error('invalid_wallet');let carry=index;for(let i=0;i<bytes.length;i++){carry+=bytes[i]*58;bytes[i]=carry&255;carry>>=8;}while(carry){bytes.push(carry&255);carry>>=8;}} for(const char of value){if(char!=='1')break;bytes.push(0);} return Buffer.from(bytes.reverse()); }
function hash(value) { return createHash('sha256').update(value).digest('hex'); }
module.exports = async function handler(request,response) {
  if(request.method!=='POST')return response.status(405).json({error:'method_not_allowed'});
  const {challengeId,signature}=request.body||{}; if(typeof challengeId!=='string'||typeof signature!=='string')return response.status(400).json({error:'challenge_and_signature_required'});
  try { const result=await withDatabaseTransaction(async client=>{const found=await client.query('SELECT id,wallet_address,message FROM auth_challenges WHERE id=$1 AND consumed_at IS NULL AND expires_at>now() FOR UPDATE',[challengeId]); const row=found.rows[0]; if(!row)return {status:401,body:{error:'challenge_expired_or_used'}}; let valid=false; try {const pub=decodeBase58(row.wallet_address); const key=Buffer.concat([Buffer.from('302a300506032b6570032100','hex'),pub]); valid=pub.length===32&&verify(null,Buffer.from(row.message),{key,format:'der',type:'spki'},Buffer.from(signature,'base64'));} catch {} if(!valid)return {status:401,body:{error:'invalid_wallet_signature'}}; await client.query('UPDATE auth_challenges SET consumed_at=now() WHERE id=$1',[row.id]); const agent=await client.query(`INSERT INTO agents (id,owner_wallet,name,persona,dflow_wallet_name,wallet_public_key) VALUES ($1,$2,'Agent Driver','UNCONFIGURED',$3,$2) ON CONFLICT (owner_wallet) DO NOTHING RETURNING id`,[randomUUID(),row.wallet_address,`auth-${row.wallet_address.slice(0,28)}`]); const resolved=agent.rows[0]|| (await client.query('SELECT id FROM agents WHERE owner_wallet=$1',[row.wallet_address])).rows[0]; const token=randomBytes(32).toString('base64url'),expiresAt=new Date(Date.now()+30*60*1000).toISOString(); await client.query('INSERT INTO agent_sessions (id,agent_id,token_hash,expires_at) VALUES ($1,$2,$3,$4)',[randomUUID(),resolved.id,hash(token),expiresAt]); return {status:201,body:{token,expiresAt}};}); return response.status(result.status).json(result.body); }
  catch(error){console.error('auth verify failed',error);return response.status(503).json({error:'authentication_unavailable'});}
};
